libstdcxx: avoid empty libstdc++ C++23 sources (#785)
seems this is a bazel shortcoming that requires manual workaround
(8.4.1, 8.7)

build libstdcxx < 16 will trigger this error
```
ERROR: /home/xinyuwang/.cache/bazel/_bazel_xinyuwang/fd6031dda7ef31c838f82253a4a0e7df/externa
l/llvm++gcc+gcc_15_2_0/BUILD.bazel:1628:11: in cc_library rule @@llvm++gcc+gcc_15_2_0//:libst
dcxx_cxx23: 
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/cc_library.bzl", line 26, column 36, in _cc_lib
rary_impl
        File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 94, column 27, in _check_s
rcs_extensions
        File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 91, column 25, in _check_f
ile_extensions
Error in fail: attribute srcs: '@@llvm++gcc+gcc_15_2_0//:libstdcxx_cxx23_sources' does not pr
oduce any cc_library srcs files
ERROR: /home/xinyuwang/.cache/bazel/_bazel_xinyuwang/fd6031dda7ef31c838f82253a4a0e7df/externa
l/llvm++gcc+gcc_15_2_0/BUILD.bazel:1628:11: Analysis of target '@@llvm++gcc+gcc_15_2_0//:libs
tdcxx_cxx23' (config: 79db54a) failed
ERROR: Analysis of target '//:gcc_15_2_0' failed; build aborted: Analysis failed

```

try 

https://github.com/comicfans/hermetic_llvm_bug_reproducer/tree/reproduce_libstdcxx_cxx23_sources
to produce this issue



seems the logic is correct but bazel's behavior is incorrect

```
filegroup(
    name = "libstdcxx_cxx23_sources",
    # GCC 16 links src/c++23/libmodulesconvenience.la into libstdc++.
    # Upstream falls back to empty sources when module compilation is not
    # available; this port uses that fallback until C++ module support is
    # modeled explicitly.
    srcs = [
        ":libstdcxx_cxx23_std_cc",
        ":libstdcxx_cxx23_std_compat_cc",
    ] if gcc_version_at_least_for(GCC_VERSION, "16.0.0") else [],
)
```