libstdcxx: avoid conflict when sandbox+shared host tmp dir (#784)
when --noincompatible_sandbox_hermetic_tmp is used, (share host tmp dir)
tmp dir with pid suffix will be duplicate since both actions inside
their own sandbox is 2, mkdir -p ignore dir exists error, then following
actions will silently rm this dir and corrupted other actions result,
makes config check result inconsist and gives wired error

```
ERROR: /home/xinyuwang/project/hermetic_llvm_libstdcxx_issue_reproducer/BUILD.bazel:11:11: Comp
iling main.cc failed: (Exit 1): clang++ failed: error executing CppCompile command (from target
 //:repro) 
  (cd /home/xinyuwang/.cache/bazel/_bazel_xinyuwang/fd6031dda7ef31c838f82253a4a0e7df/sandbox/li
nux-sandbox/5020/execroot/_main && \
  exec env - \
    PATH=/home/xinyuwang/.cache/bazelisk/downloads/sha256/3453736dc067a9b923f3066aad378282cd864
830d9ad135a45ac9c1ebc47bbae/bin:/home/xinyuwang/.local/bin:/home/xinyuwang/.local/neovim/bin:/h
ome/xinyuwang/.local/bin:/home/xinyuwang/.local/neovim/bin:/usr/local/sbin:/usr/local/bin:/usr/
sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/xinyuwang/node_modules/@wi
thgraphite/graphite-cli:/home/xinyuwang/.local/eclipse:/home/xinyuwang/.local/async-profiler/bi
n:/home/xinyuwang/.local/golang/bin:/home/xinyuwang/.cargo/bin:/home/xinyuwang/node_modules/@wi
thgraphite/graphite-cli:/home/xinyuwang/.local/eclipse:/home/xinyuwang/.local/async-profiler/bi
n:/home/xinyuwang/.local/golang/bin:/home/xinyuwang/.cargo/bin \
    PWD=/proc/self/cwd \
  external/llvm++llvm_toolchain_minimal+llvm-toolchain-minimal-linux-amd64/bin/clang++ -target 
x86_64-linux-gnu -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-
D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-ffile-compilation-dir=.' -Xclang -fno-cxx-
modules -Wno-module-import-in-extern-c '-Werror=incomplete-umbrella' -Wno-modules-import-nested
-redundant '--sysroot=/dev/null' -nostdlibinc -isystem bazel-out/k8-fastbuild/bin/external/llvm
++gcc+gcc_17_0_0/headers_include_search_directory -isystem bazel-out/k8-fastbuild/bin/external/
llvm++gcc+gcc_17_0_0/generated_host_headers_include_search_directory -isystem external/llvm++ke
rnel_headers+linux_kernel_headers_x86.6.9.12/include -isystem external/llvm++glibc+glibc_header
s_x86_64-linux-gnu.2.39/include -Xclang -internal-isystem -Xclang external/llvm++llvm+llvm-proj
ect/compiler-rt/include '-resource-dir=external/llvm++llvm_toolchain_minimal+llvm-toolchain-min
imal-linux-amd64/lib/clang/23' -Xclang -fmodule-map-file-home-is-cwd '-std=c++17' -fstack-prote
ctor -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -f
color-diagnostics -fno-omit-frame-pointer -fPIC '-frandom-seed=bazel-out/k8-fastbuild/bin/_objs
/repro/main.pic.o' -iquote . -iquote bazel-out/k8-fastbuild/bin -MD -MF bazel-out/k8-fastbuild/
bin/_objs/repro/main.pic.d -c main.cc -o bazel-out/k8-fastbuild/bin/_objs/repro/main.pic.o)
# Configuration: 42b22ad2be10ff8599ea07f29ce0e92116b69a0784037142e29ec234dbd17d87
# Execution platform: @@platforms//host:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root 
for debugging
In file included from main.cc:1:
In file included from bazel-out/k8-fastbuild/bin/external/llvm++gcc+gcc_17_0_0/headers_include_
search_directory/filesystem:54:
In file included from bazel-out/k8-fastbuild/bin/external/llvm++gcc+gcc_17_0_0/headers_include_
search_directory/bits/fs_fwd.h:35:
In file included from bazel-out/k8-fastbuild/bin/external/llvm++gcc+gcc_17_0_0/headers_include_
search_directory/system_error:44:
In file included from bazel-out/k8-fastbuild/bin/external/llvm++gcc+gcc_17_0_0/headers_include_
search_directory/iosfwd:44:
In file included from bazel-out/k8-fastbuild/bin/external/llvm++gcc+gcc_17_0_0/headers_include_
search_directory/bits/postypes.h:42:
bazel-out/k8-fastbuild/bin/external/llvm++gcc+gcc_17_0_0/headers_include_search_directory/cwcha
r:60:5: error: typedef redefinition with different types ('struct mbstate_t' vs '__mbstate_t')
   60 |   } mbstate_t;
      |     ^
external/llvm++glibc+glibc_headers_x86_64-linux-gnu.2.39/include/bits/types/mbstate_t.h:6:21: n
ote: previous definition is here
    6 | typedef __mbstate_t mbstate_t;
      |                     ^
1 error generated.
```
 
improve it by using mktemp command so this action became atomic

this issue can be reproduced by repo
https://github.com/comicfans/hermetic_llvm_bug_reproducer.
repeat clean/build simplest hello world with
`--noincompatible_sandbox_hermetic_tmp` can easily trigger it.
this error goes away after applying the patch